// <auto-generated />
using System;
using ELearning.Infastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ELearning.Infastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260414211524_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ELearning.Domain.Assistants.Assistant", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("instructor_id");

                    b.HasKey("Id")
                        .HasName("pk_assistants");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("ix_assistants_instructor_id");

                    b.ToTable("assistants", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Discounts.CodeApplicableArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_code_applicable_areas");

                    b.ToTable("code_applicable_areas", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Discounts.CodeAreas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppplicableAreaId")
                        .HasColumnType("int")
                        .HasColumnName("appplicable_area_id");

                    b.Property<string>("CodeId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code_id");

                    b.Property<string>("TargetId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("target_id");

                    b.HasKey("Id")
                        .HasName("pk_code_areas");

                    b.HasIndex("CodeId")
                        .HasDatabaseName("ix_code_areas_code_id");

                    b.HasIndex("AppplicableAreaId", "CodeId")
                        .HasDatabaseName("ix_code_areas_appplicable_area_id_code_id");

                    b.ToTable("code_areas", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Discounts.DiscountCode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<int?>("CountLimit")
                        .HasColumnType("int")
                        .HasColumnName("count_limit");

                    b.Property<int>("CurrentCount")
                        .HasColumnType("int")
                        .HasColumnName("current_count");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("discount_type");

                    b.Property<string>("ExpireType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("expire_type");

                    b.Property<DateTime?>("ExpiredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired_at_utc");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("generated_at_utc");

                    b.Property<DateTime?>("LastUsedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_used_at_utc");

                    b.Property<long>("row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_discount_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_discount_codes_code");

                    b.ToTable("discount_codes", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Enrollments.Enrollment", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at");

                    b.Property<int?>("MaxTries")
                        .HasColumnType("int")
                        .HasColumnName("max_tries");

                    b.Property<string>("PurchaseId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("purchase_id");

                    b.Property<string>("QuizId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("quiz_id");

                    b.Property<int?>("RemainingTries")
                        .HasColumnType("int")
                        .HasColumnName("remaining_tries");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_enrollments");

                    b.HasIndex("PurchaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_enrollments_purchase_id");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_enrollments_quiz_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_enrollments_session_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_enrollments_student_id");

                    b.ToTable("enrollments", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Enrollments.UserQuiz", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_in_seconds");

                    b.Property<string>("EnrollmentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("enrollment_id");

                    b.Property<int>("FinishTimeInSeconds")
                        .HasColumnType("int")
                        .HasColumnName("finish_time_in_seconds");

                    b.Property<DateTime>("IssuedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("issued_at_utc");

                    b.Property<string>("QuizId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("quiz_id");

                    b.Property<double?>("Score")
                        .HasColumnType("float")
                        .HasColumnName("score");

                    b.Property<decimal>("Threshold")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("threshold");

                    b.Property<double>("TotalScore")
                        .HasColumnType("float")
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("pk_users_quizes");

                    b.HasIndex("QuizId")
                        .HasDatabaseName("ix_users_quizes_quiz_id");

                    b.HasIndex("EnrollmentId", "QuizId")
                        .HasDatabaseName("ix_users_quizes_enrollment_id_quiz_id");

                    b.ToTable("users_quizes", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Enrollments.VideoViewTank", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<int>("BestPositionInSeconds")
                        .HasColumnType("int")
                        .HasColumnName("best_position_in_seconds");

                    b.Property<int>("DurationThreshold")
                        .HasColumnType("int")
                        .HasColumnName("duration_threshold");

                    b.Property<string>("EnrollmentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("enrollment_id");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("bit")
                        .HasColumnName("is_unlocked");

                    b.Property<DateTime?>("LastActiveAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_active_at_utc");

                    b.Property<int>("LastPositionInSeconds")
                        .HasColumnType("int")
                        .HasColumnName("last_position_in_seconds");

                    b.Property<int?>("MaxViewCount")
                        .HasColumnType("int")
                        .HasColumnName("max_view_count");

                    b.Property<int>("RemainingTankSeconds")
                        .HasColumnType("int")
                        .HasColumnName("remaining_tank_seconds");

                    b.Property<int>("TankSecondsCapacity")
                        .HasColumnType("int")
                        .HasColumnName("tank_seconds_capacity");

                    b.Property<int>("UsedViewCount")
                        .HasColumnType("int")
                        .HasColumnName("used_view_count");

                    b.Property<int>("VideoDurationSeconds")
                        .HasColumnType("int")
                        .HasColumnName("video_duration_seconds");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("video_id");

                    b.HasKey("Id")
                        .HasName("pk_videos_view_tanks");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_videos_view_tanks_video_id");

                    b.HasIndex("EnrollmentId", "VideoId")
                        .IsUnique()
                        .HasDatabaseName("ix_videos_view_tanks_enrollment_id_video_id");

                    b.ToTable("videos_view_tanks", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Exams.Exam", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_in_seconds");

                    b.Property<string>("ExamType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("exam_type");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("instructor_id");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PublishedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("published_at_utc");

                    b.Property<int>("QuestionsNumber")
                        .HasColumnType("int")
                        .HasColumnName("questions_number");

                    b.Property<string>("ResultDisplay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("result_display");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("subject_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("TotalGrades")
                        .HasColumnType("int")
                        .HasColumnName("total_grades");

                    b.HasKey("Id")
                        .HasName("pk_exams");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("ix_exams_instructor_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_exams_subject_id");

                    b.ToTable("exams", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamEnrollment", b =>
                {
                    b.Property<string>("PurchaseId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("purchase_id");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("student_id");

                    b.Property<string>("ExamId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("exam_id");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_in_seconds");

                    b.Property<DateTime?>("EnrolledOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("enrolled_on_utc");

                    b.Property<DateTime?>("FinishedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("finished_at_utc");

                    b.Property<double?>("Grade")
                        .HasColumnType("float")
                        .HasColumnName("grade");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<int>("TotalGrade")
                        .HasColumnType("int")
                        .HasColumnName("total_grade");

                    b.HasKey("PurchaseId", "StudentId", "ExamId")
                        .HasName("pk_exam_enrollments");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_exam_enrollments_exam_id");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_enrollments_id")
                        .HasFilter("[id] IS NOT NULL");

                    b.HasIndex("PurchaseId")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_enrollments_purchase_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_exam_enrollments_student_id");

                    b.ToTable("exam_enrollments", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamMcqQuestionAnswer", b =>
                {
                    b.Property<int>("AnswerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("answer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnswerId"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("answer");

                    b.Property<int?>("ExamQuestionId")
                        .HasColumnType("int")
                        .HasColumnName("exam_question_id");

                    b.HasKey("AnswerId")
                        .HasName("pk_exam_mcq_questions_answers");

                    b.HasIndex("ExamQuestionId")
                        .HasDatabaseName("ix_exam_mcq_questions_answers_exam_question_id");

                    b.ToTable("exam_mcq_questions_answers", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExamId")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("exam_id");

                    b.Property<double>("Grade")
                        .HasColumnType("float")
                        .HasColumnName("grade");

                    b.Property<string>("Question")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("question");

                    b.Property<string>("SessionQuizId")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("session_quiz_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<int?>("correct_answer_id")
                        .HasColumnType("int")
                        .HasColumnName("correct_answer_id");

                    b.HasKey("Id")
                        .HasName("pk_exam_questions");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_exam_questions_exam_id");

                    b.HasIndex("SessionQuizId")
                        .HasDatabaseName("ix_exam_questions_session_quiz_id");

                    b.HasIndex("correct_answer_id")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_questions_correct_answer_id")
                        .HasFilter("[correct_answer_id] IS NOT NULL");

                    b.ToTable("exam_questions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestionAnswer", b =>
                {
                    b.Property<string>("UserQuizId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("user_quiz_id");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int")
                        .HasColumnName("question_id");

                    b.Property<string>("Answer")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("answer");

                    b.HasKey("UserQuizId", "QuestionId")
                        .HasName("pk_exam_questions_answers");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_exam_questions_answers_question_id");

                    b.ToTable("exam_questions_answers", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Instructors.Instructor", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("bio");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("subject_id");

                    b.Property<long>("row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_instructors");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_instructors_subject_id");

                    b.ToTable("instructors", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Purchases.PaidCode", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code");

                    b.Property<DateTime?>("ExpiredAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("expired_at_utc");

                    b.Property<DateTime>("GeneratedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("generated_at_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("UsedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("used_at_utc");

                    b.Property<long>("row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_paid_codes");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_paid_codes_code");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_paid_codes_student_id");

                    b.ToTable("paid_codes", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Purchases.Purchase", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("CodeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("code_id");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("ExamId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("exam_id");

                    b.Property<string>("PaymentMethodId")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("payment_method_id");

                    b.Property<DateTime?>("PurchasedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("purchased_at_utc");

                    b.Property<DateTime?>("RefundedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("refunded_at_utc");

                    b.Property<string>("SessionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("student_id");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_paid");

                    b.HasKey("Id")
                        .HasName("pk_purchases");

                    b.HasIndex("CodeId")
                        .HasDatabaseName("ix_purchases_code_id");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_purchases_exam_id");

                    b.HasIndex("PaymentMethodId")
                        .HasDatabaseName("ix_purchases_payment_method_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_purchases_session_id");

                    b.HasIndex("StudentId", "ExamId")
                        .HasDatabaseName("ix_purchases_student_id_exam_id");

                    b.HasIndex("StudentId", "SessionId")
                        .HasDatabaseName("ix_purchases_student_id_session_id");

                    b.ToTable("purchases", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Purchases.PurchaseMethod", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_purchase_methods");

                    b.ToTable("purchase_methods", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Ratings.InstructorsRating", b =>
                {
                    b.Property<string>("InstructorId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("instructor_id");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("rating");

                    b.HasKey("InstructorId", "StudentId")
                        .HasName("pk_instructors_ratings");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_instructors_ratings_student_id");

                    b.ToTable("instructors_ratings", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Ratings.SessionsRating", b =>
                {
                    b.Property<string>("SessionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("session_id");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("id");

                    b.Property<decimal>("Rating")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("rating");

                    b.HasKey("SessionId", "StudentId")
                        .HasName("pk_sessions_ratings");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_sessions_ratings_student_id");

                    b.ToTable("sessions_ratings", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Reviews.InstructorsReview", b =>
                {
                    b.Property<string>("InstructorId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("instructor_id");

                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("student_id");

                    b.Property<string>("Review")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("review");

                    b.HasKey("InstructorId", "StudentId")
                        .HasName("pk_instructor_reviews");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_instructor_reviews_student_id");

                    b.ToTable("instructor_reviews", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Sessions.QuestionAnswerVote", b =>
                {
                    b.Property<string>("StudentId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("student_id");

                    b.Property<string>("VideoId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("video_id");

                    b.Property<string>("QuestionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("question_id");

                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("id");

                    b.Property<string>("VoteType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vote_type");

                    b.HasKey("StudentId", "VideoId", "QuestionId")
                        .HasName("pk_questions_votes");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasDatabaseName("ix_questions_votes_id")
                        .HasFilter("[id] IS NOT NULL");

                    b.HasIndex("QuestionId")
                        .HasDatabaseName("ix_questions_votes_question_id");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_questions_votes_video_id");

                    b.ToTable("questions_votes", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Sessions.Session", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_on_utc");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("description");

                    b.Property<bool>("HasQuiz")
                        .HasColumnType("bit")
                        .HasColumnName("has_quiz");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("instructor_id");

                    b.Property<DateTime?>("LastUpdatedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_updated_on_utc");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<DateTime?>("PublishedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("published_on_utc");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("subject_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<long>("row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_sessions");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("ix_sessions_instructor_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_sessions_subject_id");

                    b.ToTable("sessions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Sessions.SessionQuiz", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at_utc");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_in_seconds");

                    b.Property<string>("InstructorId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("instructor_id");

                    b.Property<int>("MaximumTries")
                        .HasColumnType("int")
                        .HasColumnName("maximum_tries");

                    b.Property<decimal>("PassingPercentage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("passing_percentage");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("SubjectId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("subject_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<int>("TotalGrades")
                        .HasColumnType("int")
                        .HasColumnName("total_grades");

                    b.Property<int>("TotalQuestions")
                        .HasColumnType("int")
                        .HasColumnName("total_questions");

                    b.HasKey("Id")
                        .HasName("pk_sessions_quizes");

                    b.HasIndex("InstructorId")
                        .HasDatabaseName("ix_sessions_quizes_instructor_id");

                    b.HasIndex("SubjectId")
                        .HasDatabaseName("ix_sessions_quizes_subject_id");

                    b.ToTable("sessions_quizes", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Sessions.Video", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<int>("DurationInSeconds")
                        .HasColumnType("int")
                        .HasColumnName("duration_in_seconds");

                    b.Property<bool>("HasPrerequisite")
                        .HasColumnType("bit")
                        .HasColumnName("has_prerequisite");

                    b.Property<bool>("IsCountedInSessionProgression")
                        .HasColumnType("bit")
                        .HasColumnName("is_counted_in_session_progression");

                    b.Property<int?>("MaxViewCount")
                        .HasColumnType("int")
                        .HasColumnName("max_view_count");

                    b.Property<int>("Order")
                        .HasColumnType("int")
                        .HasColumnName("order");

                    b.Property<string>("PrerequisiteId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("prerequisite_id");

                    b.Property<string>("SessionId")
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("session_id");

                    b.Property<decimal>("ThresholdPercentage")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("threshold_percentage");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_videos");

                    b.HasIndex("PrerequisiteId")
                        .IsUnique()
                        .HasDatabaseName("ix_videos_prerequisite_id")
                        .HasFilter("[prerequisite_id] IS NOT NULL");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_videos_session_id");

                    b.ToTable("videos", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Sessions.VideoQuestion", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("Answer")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("answer");

                    b.Property<string>("AssistantId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("assistant_id");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("session_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("student_id");

                    b.Property<string>("VideoId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("video_id");

                    b.Property<int>("Vote")
                        .HasColumnType("int")
                        .HasColumnName("vote");

                    b.HasKey("Id")
                        .HasName("pk_videos_questions");

                    b.HasIndex("AssistantId")
                        .HasDatabaseName("ix_videos_questions_assistant_id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("ix_videos_questions_session_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_videos_questions_student_id");

                    b.HasIndex("VideoId")
                        .HasDatabaseName("ix_videos_questions_video_id");

                    b.ToTable("videos_questions", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Students.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<decimal>("Wallet")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("wallet");

                    b.Property<long>("row_version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bigint")
                        .HasColumnName("row_version");

                    b.HasKey("Id")
                        .HasName("pk_students");

                    b.ToTable("students", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Subjects.Subject", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_subjects");

                    b.ToTable("subjects", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Users.User", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("city");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<string>("IdentityId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("identity_id");

                    b.Property<DateTime>("JoinedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("joined_on_utc");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("IdentityId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_identity_id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ELearning.Infastructure.Outbox.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccurredOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("occurred_on_utc");

                    b.Property<DateTime?>("ProcessedOnUtc")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_on_utc");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_messages");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("ELearning.Domain.Assistants.Assistant", b =>
                {
                    b.HasOne("ELearning.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("ELearning.Domain.Assistants.Assistant", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_assistants_users_id");

                    b.HasOne("ELearning.Domain.Instructors.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_assistants_instructors_instructor_id");
                });

            modelBuilder.Entity("ELearning.Domain.Discounts.CodeAreas", b =>
                {
                    b.HasOne("ELearning.Domain.Discounts.CodeApplicableArea", null)
                        .WithMany()
                        .HasForeignKey("AppplicableAreaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_code_areas_code_applicable_areas_appplicable_area_id");

                    b.HasOne("ELearning.Domain.Discounts.DiscountCode", null)
                        .WithMany()
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_code_areas_discount_code_code_id");
                });

            modelBuilder.Entity("ELearning.Domain.Discounts.DiscountCode", b =>
                {
                    b.OwnsOne("ELearning.Domain.Discounts.DateRange", "ExpirePeriod", b1 =>
                        {
                            b1.Property<string>("DiscountCodeId")
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("id");

                            b1.Property<DateTime?>("EndDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("expire_end_date");

                            b1.Property<DateTime?>("StartDate")
                                .HasColumnType("datetime2")
                                .HasColumnName("expire_start_date");

                            b1.HasKey("DiscountCodeId");

                            b1.ToTable("discount_codes");

                            b1.WithOwner()
                                .HasForeignKey("DiscountCodeId")
                                .HasConstraintName("fk_discount_codes_discount_codes_id");
                        });

                    b.Navigation("ExpirePeriod");
                });

            modelBuilder.Entity("ELearning.Domain.Enrollments.Enrollment", b =>
                {
                    b.HasOne("ELearning.Domain.Purchases.Purchase", null)
                        .WithOne()
                        .HasForeignKey("ELearning.Domain.Enrollments.Enrollment", "PurchaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_purchase_purchase_id");

                    b.HasOne("ELearning.Domain.Sessions.SessionQuiz", null)
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_enrollments_session_quiz_quiz_id");

                    b.HasOne("ELearning.Domain.Sessions.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_session_session_id");

                    b.HasOne("ELearning.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_enrollments_student_student_id");
                });

            modelBuilder.Entity("ELearning.Domain.Enrollments.UserQuiz", b =>
                {
                    b.HasOne("ELearning.Domain.Enrollments.Enrollment", null)
                        .WithMany()
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_users_quizes_enrollments_enrollment_id");

                    b.HasOne("ELearning.Domain.Sessions.SessionQuiz", null)
                        .WithMany()
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_users_quizes_sessions_quizes_quiz_id");
                });

            modelBuilder.Entity("ELearning.Domain.Enrollments.VideoViewTank", b =>
                {
                    b.HasOne("ELearning.Domain.Enrollments.Enrollment", null)
                        .WithMany("Tanks")
                        .HasForeignKey("EnrollmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_videos_view_tanks_enrollments_enrollment_id");

                    b.HasOne("ELearning.Domain.Sessions.Video", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_videos_view_tanks_videos_video_id");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.Exam", b =>
                {
                    b.HasOne("ELearning.Domain.Instructors.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_exams_instructor_instructor_id");

                    b.HasOne("ELearning.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_exams_subject_subject_id");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamEnrollment", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_exam_enrollments_exams_exam_id");

                    b.HasOne("ELearning.Domain.Purchases.Purchase", null)
                        .WithOne()
                        .HasForeignKey("ELearning.Domain.Exams.ExamEnrollment", "PurchaseId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_exam_enrollments_purchase_purchase_id");

                    b.HasOne("ELearning.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_exam_enrollments_student_student_id");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamMcqQuestionAnswer", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.ExamQuestion", null)
                        .WithMany("McqQuestionAnswers")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_exam_mcq_questions_answers_exam_question_exam_question_id");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestion", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany("Questions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_exam_questions_exams_exam_id");

                    b.HasOne("ELearning.Domain.Sessions.SessionQuiz", null)
                        .WithMany("Questions")
                        .HasForeignKey("SessionQuizId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_exam_questions_session_quiz_session_quiz_id");

                    b.HasOne("ELearning.Domain.Exams.ExamMcqQuestionAnswer", "CorrectAnswer")
                        .WithOne()
                        .HasForeignKey("ELearning.Domain.Exams.ExamQuestion", "correct_answer_id")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_exam_questions_exam_mcq_questions_answers_correct_answer_id");

                    b.Navigation("CorrectAnswer");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestionAnswer", b =>
                {
                    b.HasOne("ELearning.Domain.Exams.ExamQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_exam_questions_answers_exam_question_question_id");

                    b.HasOne("ELearning.Domain.Enrollments.UserQuiz", null)
                        .WithMany()
                        .HasForeignKey("UserQuizId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_exam_questions_answers_user_quiz_user_quiz_id");
                });

            modelBuilder.Entity("ELearning.Domain.Instructors.Instructor", b =>
                {
                    b.HasOne("ELearning.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("ELearning.Domain.Instructors.Instructor", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_instructors_users_id");

                    b.HasOne("ELearning.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_instructors_subjects_subject_id");

                    b.OwnsOne("ELearning.Domain.Ratings.RatingSummary", "Rating", b1 =>
                        {
                            b1.Property<string>("InstructorId")
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("id");

                            b1.Property<decimal>("Average")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("rating_average");

                            b1.Property<int>("Count")
                                .HasColumnType("int")
                                .HasColumnName("rating_count");

                            b1.HasKey("InstructorId");

                            b1.ToTable("instructors");

                            b1.WithOwner()
                                .HasForeignKey("InstructorId")
                                .HasConstraintName("fk_instructors_instructors_id");
                        });

                    b.Navigation("Rating")
                        .IsRequired();
                });

            modelBuilder.Entity("ELearning.Domain.Purchases.PaidCode", b =>
                {
                    b.HasOne("ELearning.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_paid_codes_student_student_id");
                });

            modelBuilder.Entity("ELearning.Domain.Purchases.Purchase", b =>
                {
                    b.HasOne("ELearning.Domain.Discounts.DiscountCode", null)
                        .WithMany()
                        .HasForeignKey("CodeId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_purchases_discount_codes_code_id");

                    b.HasOne("ELearning.Domain.Exams.Exam", null)
                        .WithMany()
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_purchases_exams_exam_id");

                    b.HasOne("ELearning.Domain.Purchases.PurchaseMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_purchases_purchase_method_payment_method_id");

                    b.HasOne("ELearning.Domain.Sessions.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_purchases_session_session_id");

                    b.HasOne("ELearning.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_purchases_student_student_id");

                    b.Navigation("PaymentMethod");
                });

            modelBuilder.Entity("ELearning.Domain.Ratings.InstructorsRating", b =>
                {
                    b.HasOne("ELearning.Domain.Instructors.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_instructors_ratings_instructors_instructor_id");

                    b.HasOne("ELearning.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_instructors_ratings_student_student_id");
                });

            modelBuilder.Entity("ELearning.Domain.Ratings.SessionsRating", b =>
                {
                    b.HasOne("ELearning.Domain.Sessions.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_ratings_sessions_session_id");

                    b.HasOne("ELearning.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_ratings_student_student_id");
                });

            modelBuilder.Entity("ELearning.Domain.Reviews.InstructorsReview", b =>
                {
                    b.HasOne("ELearning.Domain.Instructors.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_instructor_reviews_instructors_instructor_id");

                    b.HasOne("ELearning.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_instructor_reviews_student_student_id");
                });

            modelBuilder.Entity("ELearning.Domain.Sessions.QuestionAnswerVote", b =>
                {
                    b.HasOne("ELearning.Domain.Sessions.VideoQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_votes_video_question_question_id");

                    b.HasOne("ELearning.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_votes_student_student_id");

                    b.HasOne("ELearning.Domain.Sessions.Video", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_questions_votes_video_video_id");
                });

            modelBuilder.Entity("ELearning.Domain.Sessions.Session", b =>
                {
                    b.HasOne("ELearning.Domain.Sessions.SessionQuiz", "Quiz")
                        .WithOne()
                        .HasForeignKey("ELearning.Domain.Sessions.Session", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_sessions_session_quiz_id");

                    b.HasOne("ELearning.Domain.Instructors.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_instructors_instructor_id");

                    b.HasOne("ELearning.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_subject_subject_id");

                    b.OwnsOne("ELearning.Domain.Ratings.RatingSummary", "Rating", b1 =>
                        {
                            b1.Property<string>("SessionId")
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("id");

                            b1.Property<decimal>("Average")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("rating_average");

                            b1.Property<int>("Count")
                                .HasColumnType("int")
                                .HasColumnName("rating_count");

                            b1.HasKey("SessionId");

                            b1.ToTable("sessions");

                            b1.WithOwner()
                                .HasForeignKey("SessionId")
                                .HasConstraintName("fk_sessions_sessions_id");
                        });

                    b.Navigation("Quiz");

                    b.Navigation("Rating")
                        .IsRequired();
                });

            modelBuilder.Entity("ELearning.Domain.Sessions.SessionQuiz", b =>
                {
                    b.HasOne("ELearning.Domain.Instructors.Instructor", null)
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_quizes_instructors_instructor_id");

                    b.HasOne("ELearning.Domain.Subjects.Subject", null)
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_sessions_quizes_subject_subject_id");
                });

            modelBuilder.Entity("ELearning.Domain.Sessions.Video", b =>
                {
                    b.HasOne("ELearning.Domain.Sessions.Video", null)
                        .WithOne()
                        .HasForeignKey("ELearning.Domain.Sessions.Video", "PrerequisiteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_videos_videos_prerequisite_id");

                    b.HasOne("ELearning.Domain.Sessions.Session", null)
                        .WithMany("Videos")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_videos_sessions_session_id");
                });

            modelBuilder.Entity("ELearning.Domain.Sessions.VideoQuestion", b =>
                {
                    b.HasOne("ELearning.Domain.Assistants.Assistant", null)
                        .WithMany()
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_videos_questions_assistants_assistant_id");

                    b.HasOne("ELearning.Domain.Sessions.Session", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_videos_questions_sessions_session_id");

                    b.HasOne("ELearning.Domain.Students.Student", null)
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_videos_questions_students_student_id");

                    b.HasOne("ELearning.Domain.Sessions.Video", null)
                        .WithMany()
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_videos_questions_videos_video_id");
                });

            modelBuilder.Entity("ELearning.Domain.Students.Student", b =>
                {
                    b.HasOne("ELearning.Domain.Users.User", null)
                        .WithOne()
                        .HasForeignKey("ELearning.Domain.Students.Student", "Id")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_students_users_id");
                });

            modelBuilder.Entity("ELearning.Domain.Enrollments.Enrollment", b =>
                {
                    b.Navigation("Tanks");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.Exam", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("ELearning.Domain.Exams.ExamQuestion", b =>
                {
                    b.Navigation("McqQuestionAnswers");
                });

            modelBuilder.Entity("ELearning.Domain.Sessions.Session", b =>
                {
                    b.Navigation("Videos");
                });

            modelBuilder.Entity("ELearning.Domain.Sessions.SessionQuiz", b =>
                {
                    b.Navigation("Questions");
                });
#pragma warning restore 612, 618
        }
    }
}
